language: swift
osx_image: xcode11

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=DragDropUI.xcworkspace
  - SCHEME=DragDropUI
  - SDK=iphonesimulator13.0
  - RUN_TESTS="YES"
  - POD_LINT="NO"
  matrix:
    - DESTINATION="OS=13.0,name=iPhone 11"
    - DESTINATION="OS=13.0,name=iPhone 8"
    - DESTINATION="OS=13.0,name=iPad Pro (11-inch)"

before_install:
- rm -rf /Users/travis/Library/Developer/Xcode/DerivedData/DragDropUI-*/
- rvm use $RVM_RUBY_VERSION

install:
- bundle install
- pod install

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

# Build in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

after_success: slather
